### ISSUE TITLE
Problem z registracijo uporabnika

### ISSUE THREAD

**Issue by mateabt** [mateabt/OPB-Potniski-promet#1]
![error](https://github.com/mateabt/OPB-Potniski-promet/assets/47794374/a9e62f18-83e1-4fd9-8dbb-d52eb30dc4e8)

**Comment by gasperxy** [comment]
Živjo,

Problem, ki ga vidiš se zgodi zato ker v isti transakciji izvedeš 2 querya pri tem pa se zgodi nek error pri prvem queryu. 
Konkretno se najprej izvede query: `SELECT * FROM oseba WHERE uporabnisko_ime = %s` nato pa še `INSERT INTO oseba
                (uporabnisko_ime,ime,priimek,datum_rojstva,geslo)
                VALUES (%s, %s, %s, %s, %s)`

Error se zgodi že pri prvem.

Problem imaš, ker v tvoji bazi ni nobene tabele, oziroma te tabele niso vidne uporabniku javnost s katerim se povezuješ na bazo. Najprej je potrebno ustvarit vse potrebne tabele, potem moraš uporabniku javnost dodati dostop do baze in tabel ter oparacij na tabelah (kot smo to naredili na vajah [https://ucilnica.fmf.uni-lj.si/mod/page/view.php?id=62935](url))
