### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by mateabt** [mateabt/OPB-Potniski-promet#2]
Živjo,

projekt sem končala, manjše probleme sem imela le z filtriranjem cen ter mesta prek bajnderja ki dela le če napišem url
 (na primer http://localhost:8080/cena?max_price_enosmerna=20&max_price_povratna=30) ne pa prek gumba za filtriranje

**Comment by gasperxy** [comment]
Živjo,

Problem je v tem, da na formi, ki jo uporabljaš za filtriranje ne uporabiš url metode. Če želiš, da ti bo delovalo na Binderju, moraš za vse klice (submit form, get, post, redirect,..) uporabljat url() funkcijo. Enak problem imaš pri vlakih.

Predlagam ti še to, da so izbori za filtre nad tabelo in ne pod njo. Uporabniki namreš sedaj te filtrirne vrstice morda sploh ne opazijo (vsaj ja ne nisem takoj).

Nekaj težav sem ugotovil tudi pri dodajanju delodajalcev. ID stolpec od delodajalca ni nekaj, kar bi moral izpolnit uporabnik. ID stolpec bi moral biti tipa Serial, kar pomeni, da se ob vnosu v bazo avtomatsko generira. To bi bilo potrebno popravit.
Prav tako imaš pri delodajalcih  za dodajanje napisano: Dodaj delodajalca, potem pa imaš vpisano vnesi ime skupine. Ali je delodajalec isto kot skupina? Enaka težava tudi pri editiranju. Predlagam, da se tole poimenovanje uskladi.

Lp,
Gašper

**Comment by mateabt** [comment]
Živjo,

Popravila sem napake ter dala filtre nad tabele . Sedaj bi moralo delovati vse.

Lp,Matea

**Comment by gasperxy** [comment]
Živjo,

Super, potem pa potrjujem projekt @jaanos .
